# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from main import Ui_MainWindow


class LoginWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Loginwindow")
        MainWindow.resize(468, 545)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.loginbutton = QtWidgets.QPushButton(self.centralwidget)
        self.loginbutton.setGeometry(QtCore.QRect(170, 340, 111, 31))
        self.loginbutton.setObjectName("loginbutton")
        self.loginbutton.clicked.connect(self.tomainmenu)
        # self.loginbutton.clicked.connect(MainWindow.close) this does work...

        self.closebutton = QtWidgets.QPushButton(self.centralwidget)
        self.closebutton.setGeometry(QtCore.QRect(170, 380, 111, 31))
        self.closebutton.setObjectName("closebutton")
        self.closebutton.clicked.connect(self.closeconfirm)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 60, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 180, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")

        self.passwordbox = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordbox.setGeometry(QtCore.QRect(130, 230, 201, 31))
        self.passwordbox.setObjectName("passwordbox")
        self.passwordbox.setEchoMode(QtWidgets.QLineEdit.Password)

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 468, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.actionLock = QtWidgets.QAction(MainWindow)
        self.actionLock.setObjectName("actionLock")
        self.actionDarkSky_Weather = QtWidgets.QAction(MainWindow)
        self.actionDarkSky_Weather.setObjectName("actionDarkSky_Weather")

        self.actionLocal_Facilities = QtWidgets.QAction(MainWindow)
        self.actionLocal_Facilities.setObjectName("actionLocal_Facilities")

        self.actionNews_Scanner = QtWidgets.QAction(MainWindow)
        self.actionNews_Scanner.setObjectName("actionNews_Scanner")

        self.actionProperty_Datascraper = QtWidgets.QAction(MainWindow)
        self.actionProperty_Datascraper.setObjectName("actionProperty_Datascraper")

        self.actionPolscraper = QtWidgets.QAction(MainWindow)
        self.actionPolscraper.setObjectName("actionPolscraper")

        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuMenu.addAction(self.actionExit)

        self.menubar.addAction(self.menuMenu.menuAction())
        self.label_2.setBuddy(self.passwordbox)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Security Check"))

        self.loginbutton.setText(_translate("MainWindow", "OPEN"))
        self.closebutton.setText(_translate("MainWindow", "CLOSE"))
        self.label.setText(_translate("MainWindow", "PYTHON CONTROL PANEL"))
        self.label_2.setText(_translate("MainWindow", "ENTER PASSWORD"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))

        self.actionLock.setText(_translate("MainWindow", "Lock"))
        self.actionLock.setStatusTip(_translate("MainWindow", "Lock this computer"))
        self.actionLock.setShortcut(_translate("MainWindow", "Ctrl+L"))

        self.actionDarkSky_Weather.setText(_translate("MainWindow", "DarkSky Weather"))
        self.actionLocal_Facilities.setText(_translate("MainWindow", "Local Facilities"))
        self.actionNews_Scanner.setText(_translate("MainWindow", "News Scanner"))
        self.actionProperty_Datascraper.setText(_translate("MainWindow", "Property Datascraper"))
        self.actionPolscraper.setText(_translate("MainWindow", "Polscraper"))

        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Close the application"))

    def tomainmenu(self):
        # if self.passwordbox.text() == "correct":
        self.main_menu=QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.main_menu)
        self.main_menu.show()
        MainWindow.close()

    def closeconfirm(self):
        cfm = QMessageBox()
        cfm.setWindowTitle("Close PCP?")
        cfm.setText("Confirm if you want to close the Python Control Panel")
        cfm.setIcon(QMessageBox.Information)
        cfm.setStandardButtons(QMessageBox.Close | QMessageBox.Cancel)
        cfm.setDefaultButton(QMessageBox.Cancel)

        cfm.buttonClicked.connect(self.closeprogram)
        x = cfm.exec_()

    def closeprogram(self, i):
        order = i.text()
        if order == 'Close':
            exit()
        else:
            print(i.text())





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = LoginWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
