# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboX = QtWidgets.QComboBox(self.centralwidget)
        self.comboX.setGeometry(QtCore.QRect(10, 110, 261, 151))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboX.setFont(font)
        self.comboX.setObjectName("comboX")
        self.comboX.addItem("")
        self.comboX.addItem("")
        self.comboY = QtWidgets.QComboBox(self.centralwidget)
        self.comboY.setGeometry(QtCore.QRect(520, 100, 231, 171))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboY.setFont(font)
        self.comboY.setObjectName("comboY")
        self.comboY.addItem("")
        self.comboY.addItem("")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(290, 330, 121, 51))
        self.submit.setObjectName("submit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 120, 181, 141))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuPrograms = QtWidgets.QMenu(self.menubar)
        self.menuPrograms.setObjectName("menuPrograms")
        self.menuAPIs = QtWidgets.QMenu(self.menubar)
        self.menuAPIs.setObjectName("menuAPIs")
        self.menuComputer = QtWidgets.QMenu(self.menubar)
        self.menuComputer.setObjectName("menuComputer")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLock = QtWidgets.QAction(MainWindow)
        self.actionLock.setObjectName("actionLock")
        self.actionDarkSky_Weather = QtWidgets.QAction(MainWindow)
        self.actionDarkSky_Weather.setObjectName("actionDarkSky_Weather")
        self.actionLocal_Facilities = QtWidgets.QAction(MainWindow)
        self.actionLocal_Facilities.setObjectName("actionLocal_Facilities")
        self.actionNews_Scanner = QtWidgets.QAction(MainWindow)
        self.actionNews_Scanner.setObjectName("actionNews_Scanner")
        self.actionProperty_Datascraper = QtWidgets.QAction(MainWindow)
        self.actionProperty_Datascraper.setObjectName("actionProperty_Datascraper")
        self.actionPolscraper = QtWidgets.QAction(MainWindow)
        self.actionPolscraper.setObjectName("actionPolscraper")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuMenu.addAction(self.actionExit)
        self.menuPrograms.addAction(self.actionNews_Scanner)
        self.menuPrograms.addAction(self.actionProperty_Datascraper)
        self.menuPrograms.addAction(self.actionPolscraper)
        self.menuAPIs.addAction(self.actionDarkSky_Weather)
        self.menuAPIs.addAction(self.actionLocal_Facilities)
        self.menuComputer.addAction(self.actionLock)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuPrograms.menuAction())
        self.menubar.addAction(self.menuAPIs.menuAction())
        self.menubar.addAction(self.menuComputer.menuAction())

        self.comboX.addItem("Hello")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboX.setItemText(0, _translate("MainWindow", "0"))
        self.comboX.setItemText(1, _translate("MainWindow", "1"))
        self.comboY.setItemText(0, _translate("MainWindow", "0"))
        self.comboY.setItemText(1, _translate("MainWindow", "1"))
        self.submit.setText(_translate("MainWindow", "submit"))
        self.label.setText(_translate("MainWindow", "X OR Y = "))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuPrograms.setTitle(_translate("MainWindow", "Programs"))
        self.menuAPIs.setTitle(_translate("MainWindow", "APIs"))
        self.menuComputer.setTitle(_translate("MainWindow", "Computer"))
        self.actionLock.setText(_translate("MainWindow", "Lock"))
        self.actionLock.setStatusTip(_translate("MainWindow", "Lock this computer"))
        self.actionLock.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionDarkSky_Weather.setText(_translate("MainWindow", "DarkSky Weather"))
        self.actionLocal_Facilities.setText(_translate("MainWindow", "Local Facilities"))
        self.actionNews_Scanner.setText(_translate("MainWindow", "News Scanner"))
        self.actionProperty_Datascraper.setText(_translate("MainWindow", "Property Datascraper"))
        self.actionPolscraper.setText(_translate("MainWindow", "Polscraper"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Close the application"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
